apiVersion: v2
name: kubernetes-external-secrets
version: 8.6.0
appVersion: 8.6.0
description: "Kubernetes External Secrets CustomResourceDefinition and controller"
keywords:
  - kubernetes-external-secrets
  - secrets
home: https://github.com/jdziat/kubernetes-external-secrets
sources:
  - https://github.com/jdziat/kubernetes-external-secrets
maintainers:
  - name: jdziat
    url: https://github.com/jdziat
